Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls')),
]

records/urls.py
"""定义records的URL模式"""
from django.urls import path
from . import views


app_name = 'records'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # notes
    path('<str:note_topic>/<str:note_title>/', views.title, name='note'),
    # 向我发送邮件
    path('email/', views.email, name='email'),

    # 表单信息
    # 晨午晚检注册
    path('morninng_night_login/', views.morning_night_login, name='morning_night_login'),
]

records/models.py
from django.db import models
from typing import Text
# Create your models here.


# 用于存储主题
class Topic(models.Model):
    """需要存储的主题"""
    text = models.CharField(max_length=200)  # 设置最大限制
    create_date = models.DateTimeField(auto_now_add=True)  # 创建时间
    update_date = models.DateTimeField(auto_now=True)  # 修改时间

    class Meta:
        verbose_name = 'Topic'
        verbose_name_plural = verbose_name

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Note(models.Model):
    """记录文本"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='title', max_length=100)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)  # 创建时间
    update_date = models.DateTimeField(auto_now=True)  # 修改时间

    class Meta:
        verbose_name_plural = 'note'

    def __str__(self):
        return self.title


class Excerpts(models.Model):
    """记录名言警句"""
    origin = models.CharField(verbose_name='origin', max_length=100)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)  # 创建时间
    update_date = models.DateTimeField(auto_now=True)  # 修改时间

    class Meta:
        verbose_name_plural = 'origin'

    def __str__(self):
        return self.origin

records/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages
from .models import Note, Excerpts
from .myscript.morning_night_login import Morning_punch
import pymysql, time, smtplib
from email.mime.text import MIMEText  # 专门发送正文
from email.mime.multipart import MIMEMultipart  # 发送多个部分
# Create your views here.


def send(receiver, message):
    send_user = ''  # 发件人
    password = ''  # 密码
    receive_users = receiver  # 收件人，可为list
    subject = '回复'  # 邮件主题
    email_text = message  # 邮件正文
    server_address = 'smtp.qq.com'  # 服务器地址
    # 构造一个邮件体：正文 附件
    msg = MIMEMultipart()
    msg['Subject'] = subject  # 主题
    msg['From'] = send_user  # 发件人
    msg['To'] = receive_users  # 收件人
    # 构建正文
    part_text = MIMEText(email_text)
    msg.attach(part_text)  # 把正文加到邮件体里面去
    # 发送邮件 SMTP
    smtp = smtplib.SMTP(server_address, 587)  # 连接服务器，SMTP_SSL是安全传输
    smtp.login(send_user, password)
    smtp.sendmail(send_user, receive_users, msg.as_string())  # 发送邮件
    print('邮件发送成功！')


def index(request):
    # context = {'topics': topics, 'notes': notes}

    notes = Note.objects.all().order_by('-update_date')
    excerpts = Excerpts.objects.all().order_by('update_date')
    context = {'notes': notes, 'excerpts': excerpts}
    return render(request, 'records/index.html', context)


def title(request, note_topic, note_title):
    """晨午晚检"""
    if note_title == '模拟登录-自动填报' and note_topic == 'python':
        return render(request, 'records/morning.html')
    elif note_title == 'Django-blog搭建' and note_topic == 'python':
        return render(request, 'records/first_note.html')


def email(request):
    # 向我发送邮件:
    if request.method == 'POST':
        sender = request.POST['email']
        main_text = request.POST['main_text']
        send('', sender+'\n'+main_text)
        messages.error(request, '成功')
        return HttpResponseRedirect('/email/')
    else:
        return render(request, 'records/email.html')


def morning_night_login(request):
    # 注册晨午晚检
    def save_data(username, password, email, enable):
        # 存储信息
        db = pymysql.connect(host='', user='', password='', port=, db='')
        cursor = db.cursor()
        sql = 'CREATE TABLE IF NOT EXISTS user_data (record_date VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) ' \
              ', enable VARCHAR(255) NOT NULL)'
        cursor.execute(sql)
        tm = time.localtime()
        date = str(tm.tm_year) + '-' + str(tm.tm_mon) + '-' + str(tm.tm_mday) + '-' + str(tm.tm_hour) + '-' + str(
            tm.tm_min)
        cursor = db.cursor()
        data = {'record_date': date, 'username': username, 'password': password,
                'email': email, 'enable': enable}
        table = 'user_data'
        keys = ', '.join(data.keys())
        values = ', '.join(['%s'] * len(data))
        sql = f'INSERT INTO {table}({keys}) values ({values})'
        try:
            if cursor.execute(sql, tuple(data.values())):
                print('Successful')
                db.commit()
        except:
            print('Failed')
            db.rollback()
        db.close()

    if request.method == 'POST':
        user_username = request.POST['user_username']
        user_password = request.POST['user_password']
        user_email = request.POST['user_email']
        demo = Morning_punch(user_username, user_password)
        if demo.run() == '操作成功' or demo.run() == '您已上报过' or demo.run() == '未到上报时间':
            if user_email == '':
            user_email = False
            enable = False
            else:
                enable = True
                try:
                    send(user_email, '已完成， 如需取消通知或停止使用，请向本邮箱发送信件。')
                except:
                    messages.error(request, '邮箱错误')
                    return HttpResponseRedirect("/python/模拟登录-自动填报/")
            save_data(user_username, user_password, user_email, enable)
            messages.error(request, '成功')
            return HttpResponseRedirect("/python/模拟登录-自动填报/")
        else:
            print(demo.run())
            messages.error(request, '账号或密码不正确')
            return HttpResponseRedirect("/python/模拟登录-自动填报/")

templates/records/base.html
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>hyy</title>

    <!--Bootstrap-->
    {% bootstrap_css %}
    <!--logo字体-->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">  </head>
  <body>
    <div class="container">
      <div class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="link-abstract">abstract</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark">cbxqt</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
{#            <a class="link-secondary" href="#" aria-label="Search">#}
{#              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>#}
{#            </a>#}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'records:index' %}">Home</a>
          </div>
        </div>
      </div>
    </div>

    {% block content %} {% endblock content %}

    <footer class="blog-footer">
      <p>Designed by hyy<br>
        <a href="#">Back to top</a>
      </p>
    </footer>
  </body>
  <style>
    .blog-header{
      line-height: 1;
      border-bottom: 1px solid #e5e5e5;
    }

    .blog-header-logo{
      font-family: "Playfair Display", Georgia, "Times New Roman", serif/*rtl:Amiri, Georgia, "Times New Roman", serif*/;
      font-size: 3rem;
    }

    .blog-header-logo {
      text-decoration: none;
    }
    h1, h2, h3, h4, h5, h6 {
      font-family: Amiri, Georgia, "Times New Roman", serif;
    }
    .blog-footer {
       padding: 2.5rem 0;
       color: #727272;
       text-align: center;
       background-color: #f9f9f9;
       border-top: .05rem solid #e5e5e5;
      }

  </style>

templates/records/email.html
{% extends 'records/base.html' %}
{% block content %}
    <div class="container">
        <a class="text-decoration-none text-muted">
            <p class="text-center p-5 col-12" style="font-size: 40px">
                cbxqt@qq.com
            </p>
        </a>
        <form method="post" action="{% url 'records:email' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleEmail1">Your Email</label>
                <input name="email" class="form-control" id="exampleEmail1" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="text">正文</label>
                <textarea name="main_text" class="form-control" id="text" style="height: 400px"></textarea>
            </div>
            <br>
            <button type="submit" class="btn btn-primary" style="left: 50%">Submit</button>
        </form>
    </div>
{% if messages %}
    <script>
        {% for msg in messages %}
        alert('{{ msg }}');
        {%  endfor %}
    </script>
{% endif %}
{% endblock %}

templates/records/first_note.html
{% extends 'records/base.html' %}
{% block content %}
    <div class="container">
        <a class="col-12 text-center p-5">
            This is my first note!
        </a>
    </div>
{% endblock %}

templates/records/index.html
{% extends "records/base.html" %}
{% block content %}
    <main class="container">
        <div class="p-4 p-md-5 mb-4 text-white round bg-dark">
            <div class="col-md-7 px-0">
                <h1 class="display-5 fst-italic">Welcome to my first blog!</h1>
                <p class="lead my-3">This Blog is mainly used to record some notes I usually study, as well as some
                    feelings about books and movies.</p>
                <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
            </div>
        </div>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Detailed information
                </h3>
                {% for note in notes %}
                    <div class="row">
                        <div class="col-12 py-3">
                            <div class="card" style="width: auto;">
                                <div class="card-header"><a
                                        href={% url 'records:note' note.topic.text note.title %}>{{ note.title }}</a>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">{{ note.text }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">About</h4>
                        <p class="mb-0">Some excerpts</p>
                    </div>

                    <div class="p-4">
                        <h4 class="fst-italic">Archives</h4>
                        {% for excerpt in excerpts %}
                            <ol class="list-unstyled mb-0">
                                <li>
                                    <a>{{ excerpt.text }}</a>
                                    <small>——《{{ excerpt.origin }}》</small>
                                </li>
                            </ol>
                        {% endfor %}
                    </div>

                    <div class="p-4">
                        <h4 class="fst-italic">Elsewhere</h4>
                        <ol class="list-unstyled">
                            <li><a href="{% url 'records:email' %}">Email</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/records/morning.html
{% extends "records/base.html" %}
{% block content %}
    <main class="container">
        <h5 class="text-monospace">
            <br>
            自动填报晨午晚检虽然很简单实现，但是难免会有一点麻烦，这里提供一个接口，大家直接填入自己的账号密码即可，之后会在每天早8点与13点
            各填报一次，定位为南校区。如果你愿意的话可以留下你的邮箱，我会在每天填报完后为你发送一份邮件。
        </h5>
        <form class="col-5" method="post" action="{% url 'records:morning_night_login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input name="user_username" class="form-control" id="username" aria-describedby="emailHelp">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input name="user_password" class="form-control" id="password">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <small id="emailHelp" class="form-text text-muted">(选填)</small>
                <input name="user_email" class="form-control" id="email">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <h5 class="text-monospace">
            <br>
            <br>
            这里给出了最简单的代码，因为网站基本没有任何反爬措施，所以我写的很简单，甚至没有加请求头。<br><br>
            前提知识:了解python基本语法，安装requests库
            <a style="font-size: medium">(pip install requests)</a>
        </h5>
        <h5>
            主要步骤:<br>
            <a>
            一、登录 &nbsp;&nbsp;&nbsp;
            二、查看所需提交信息 &nbsp;&nbsp;&nbsp;
            三、发送信息 &nbsp;&nbsp;&nbsp;
            </a>
        </h5>
        <br>
        <br>
        <h5>源码如下:</h5>
        <pre>
    import requests
    import time


    login_url = 'https://xxcapp.xidian.edu.cn/uc/wap/login/check'
    url = 'https://xxcapp.xidian.edu.cn/xisuncov/wap/open-report/save'
    username = []
    password = []
    for i in range(len(username)):
        session = requests.session()
        login_data = {
            'username': username[i],
            'password': password[i],
        }
        session.post(url=login_url, data=login_data)

        data = {
            'sfzx': '1',
            'tw': '1',
            'area': '陕西省 西安市 长安区',
            'city': '西安市',
            'province': '陕西省',
            'address': '陕西省西安市长安区韦曲街道学而思培优(西长安街校区)',
            'geo_api_info': '{"type":"complete","position":{"Q":34.158996853299,"R":108.90904676649399,"lng":108.909047,"lat":34.158997},"location_type":"html5","message":"Get ipLocation failed.Get geolocation success.Convert Success.Get address success.","accuracy":8094.548535841807,"isConverted":true,"status":1,"addressComponent":{"citycode":"029","adcode":"610116","businessAreas":[{"name":"韦曲","id":"610116","location":{"Q":34.162202,"R":108.93736899999999,"lng":108.937369,"lat":34.162202}}],"neighborhoodType":"","neighborhood":"","building":"","buildingType":"","street":"西长安街","streetNumber":"599号","country":"中国","province":"陕西省","city":"西安市","district":"长安区","towncode":"610116001000","township":"韦曲街道"},"formattedAddress":"陕西省西安市长安区韦曲街道学而思培优(西长安街校区)","roads":[],"crosses":[],"pois":[],"info":"SUCCESS"}',
            'sfcyglq': '0',
            'sfyzz': '0',
            'qtqk': '',
            'ymtys': '0',
        }
        res = session.post(url=url, data=data).json()
        print(username[i], end='--')
        print(time.asctime(time.localtime(time.time())), end='--')
        print(res['m'])
    </pre>
    </main>
    {% if messages %}
    <script>
        {% for msg in messages %}
        alert('{{ msg }}');
        {% endfor %}
    </script>
    {% endif %}
{% endblock %}